#include "component.h"
#include <stdint.h>
#include <string.h>

#undef DEBUG
#include "Ifx_Types.h"
#include "IfxStm.h"
#include "Ifx_reg.h"
#include "IfxScuRcu.h"
#include "Ifx_Lwip.h"
#include "lwip/udp.h"
#include "lwip/ip.h"
#include "lwip/init.h"
#include "lwip/netif.h"
#include "lwip/timeouts.h"
#include "lwip/ip_addr.h"
#include "Ifx_Types.h"
#include "IfxStm.h"
#include "Ifx_reg.h"
#include "IfxScuRcu.h"
#include "IfxGeth_Eth.h"
#include "Ifx_Console.h"
#include "Configuration.h"
#include "ConfigurationIsr.h"
#include "Ifx_Lwip.h"

struct EthernetNodeIpv4_t{
  const char* addr;
  uint32_t port;
  uint8_t padding[5];
};

union EthernetNodeIpv4_h_t_conv{
  EthernetNodeIpv4_h* hidden;
  struct EthernetNodeIpv4_t* clear;
};

union EthernetNodeIpv4_h_t_conv_const{
  const EthernetNodeIpv4_h* hidden;
  const struct EthernetNodeIpv4_t* clear;
};

char __assert_size_ethernet[sizeof(EthernetNodeIpv4_h)==sizeof(struct EthernetNodeIpv4_t)?1:-1];
char __assert_align_ethernet[RACEUP_ALIGNOF(EthernetNodeIpv4_h)==RACEUP_ALIGNOF(struct EthernetNodeIpv4_t)?1:-1];

static uint8_t INIT_DONE = 0;
static struct udp_pcb *G_PCB;                                                  /* Pointer to the TCP protocol control block    */


int8_t hardware_ethernet_udp_init(
    EthernetNodeIpv4_h* const restrict self __attribute__((__unused__)),
    const IpAddrIpV4Port* const addr __attribute__((__unused__)))
{
  union EthernetNodeIpv4_h_t_conv conv = {self};
  struct EthernetNodeIpv4_t* p_self = conv.clear;
  ip_addr_t remote_ip;
  IfxStm_CompareConfig stmCompareConfig;                                  /* STM Configuration declaration                */

  if (!INIT_DONE)
  {

    IfxStm_initCompareConfig(&stmCompareConfig);                            /* Initialize a default configuration for STM   */

    stmCompareConfig.triggerPriority     = ISR_PRIORITY_OS_TICK;            /* Priority of the interrupt generated by STM   */
    stmCompareConfig.comparatorInterrupt = IfxStm_ComparatorInterrupt_ir0;  /* Select the request source 0                  */
    stmCompareConfig.ticks               = IFX_CFG_STM_TICKS_PER_MS * 10;   /* First interrupt shall occur after 10 ms      */
    stmCompareConfig.typeOfService       = IfxSrc_Tos_cpu0;                 /* CPU2 serves the interrupts                   */

    IfxStm_initCompare(&MODULE_STM0, &stmCompareConfig);                    /* Initialize the Compare functionality         */

    IfxGeth_enableModule(&MODULE_GETH);                     /* Enable Gigabit Ethernet Media Access Controller (GETH) module*/

    /* Define a MAC Address */
    eth_addr_t ethAddr;
    ethAddr.addr[0] = 0xDE;
    ethAddr.addr[1] = 0xAD;
    ethAddr.addr[2] = 0xBE;
    ethAddr.addr[3] = 0xEF;
    ethAddr.addr[4] = 0xFE;
    ethAddr.addr[5] = 0xED;

    Ifx_Lwip_init(ethAddr);                                 /* Initialize LwIP with the MAC address                         */

    INIT_DONE = 1;
  }

  G_PCB = udp_new();
  udp_bind_netif (G_PCB, Ifx_Lwip_getNetIf());

  if (!G_PCB)
  {
    serial_write_str("error init udb");
    return -1;
  }

  ipaddr_aton(addr->addr, &remote_ip);
  p_self->addr = addr->addr;
  p_self->port = addr->port;


  return 0;
}

void hardware_ethernet_update(void)
{
  Ifx_Lwip_pollTimerFlags();                          /* Poll LwIP timers and trigger protocols execution if required */
  Ifx_Lwip_pollReceiveFlags();                        /* Receive data package through ETH                             */
}

int8_t hardware_ethernet_udp_send(const EthernetNodeIpv4_h* const restrict self __attribute__((__unused__)),
    const UdpIpv4Mex* const restrict data __attribute__((__unused__)))
{
  union EthernetNodeIpv4_h_t_conv_const conv = {self};
  const struct EthernetNodeIpv4_t* p_self = conv.clear;
  ip_addr_t dest_ip = {0};

  if(!INIT_DONE)
  {
      return -1;
  }

  struct pbuf packet = {
    .len = data->data_length,
    .tot_len = data->data_length,
    .payload = (void*)data->raw_data,
    .ref = 0,
  };

  ipaddr_aton(p_self->addr, &dest_ip);
  udp_sendto(G_PCB, &packet, &dest_ip, p_self->port);

  return 0;
}

void  hardware_ethernet_udp_free(EthernetNodeIpv4_h* self __attribute__((__unused__)))
{
  udp_remove(G_PCB);
  return;
}

/* This interrupt is raised by the STM0 */
IFX_INTERRUPT (updateLwIPStackISR, 2, ISR_PRIORITY_OS_TICK);
/* ISR to update LwIP stack */
void updateLwIPStackISR(void)
{
    /* Configure STM to generate an interrupt in 1 ms */
    IfxStm_increaseCompare(&MODULE_STM0, IfxStm_Comparator_0, IFX_CFG_STM_TICKS_PER_MS);

    g_TickCount_1ms++;                                      /* Increase LwIP system time                                    */

    Ifx_Lwip_onTimerTick();                                 /* Every 1 ms LwIP timers are increased for all the enabled                                                            * protocols (ARP, TCP, DHCP, LINK)                             */
}
