/**********************************************************************************************************************
 * \file UART_VCOM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 *company in which ordinary course of business you are acting and (ii) Infineon
 *Technologies AG or its licensees. If and as long as no such terms of use are
 *agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 *and to permit third-parties to whom the Software is furnished to do so, all
 *subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer, must
 *be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 *solely in the form of machine-executable object code generated by a source
 *language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 *ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "UART_Logging.h"

#include <stdatomic.h>
#include <stdio.h>

#include "component.h"
#include <stdint.h>
#include <string.h>



/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define SERIAL_PIN_RX           IfxAsclin0_RXA_P14_1_IN                     /* RX pin of the board                  */
#define SERIAL_PIN_TX           IfxAsclin0_TX_P14_0_OUT                     /* TX pin of the board                  */

#define INTPRIO_ASCLIN0_TX      19                                          /* Priority of the ISR                  */

#define ASC_TX_BUFFER_SIZE      64                                          /* Definition of the buffer size        */

atomic_bool LOCK_SERIAL;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

int8_t hardware_init_serial(void)
{
  return 0;
}

int8_t serial_setup(const uint32_t freq)
{
  (void) freq;
  initUART();
  return 0;
}

int8_t serial_read(uint8_t* restrict const o_buffer __attribute__((__unused__)),
        const uint32_t buffer_size __attribute__((__unused__)))
{
    return -1;
}

int8_t serial_write_str(const char* const restrict buffer __attribute__((__unused__)))
{
  char clear_line[] = "\n\r";
  Ifx_SizeT new_line_size = sizeof(clear_line);
  serial_write_raw(buffer);
  sendUARTMessage(clear_line, new_line_size);      /* Send function            */
  return 0;
}

#define TEMPLATE_WRITE_DIG(DIG_TYPE, FORMAT)\
int8_t serial_write_##DIG_TYPE(const DIG_TYPE __##DIG_TYPE)\
{\
  char string[12] = {0};\
  sprintf(string, FORMAT, __##DIG_TYPE);\
  serial_write_raw(string);\
  return 0;\
}

TEMPLATE_WRITE_DIG(uint8_t, "%u")
TEMPLATE_WRITE_DIG(uint16_t, "%u")
TEMPLATE_WRITE_DIG(uint32_t, "%lu")
TEMPLATE_WRITE_DIG(int8_t, "%d")
TEMPLATE_WRITE_DIG(int16_t, "%d")
TEMPLATE_WRITE_DIG(int32_t, "%ld")
TEMPLATE_WRITE_DIG(float, "%0.5f")

int8_t serial_write_raw(const char* const restrict buffer __attribute__((__unused__)))
{
  while(atomic_load(&LOCK_SERIAL));
  atomic_store(&LOCK_SERIAL, 1);
  Ifx_SizeT count = strlen(buffer);                                               /* Size of the message                      */
  sendUARTMessage(buffer, count);      /* Send function            */
  //IfxAsclin_Asc_write(&g_asc, buffer, &count, TIME_INFINITE);         /* Transfer of data                         */
  atomic_store(&LOCK_SERIAL, 0);
  return 0;
}
