set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR tricore)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(NOT DEFINED ENV{TRICORE_LLVM})
  message(FATAL_ERROR "TRICORE_LLVM is not set; export TRICORE_LLVM to the LLVM TriCore toolchain root.")
endif()

set(TRICORE_LLVM_ROOT "$ENV{TRICORE_LLVM}")
set(TRICORE_LLVM_BIN  "${TRICORE_LLVM_ROOT}/bin")

set(CMAKE_C_COMPILER   "${TRICORE_LLVM_BIN}/clang")
set(CMAKE_ASM_COMPILER "${TRICORE_LLVM_BIN}/clang")
set(CMAKE_CXX_COMPILER "${TRICORE_LLVM_BIN}/clang")
set(CMAKE_LINKER       "${TRICORE_LLVM_BIN}/clang")
set(CMAKE_OBJCOPY      "${TRICORE_LLVM_BIN}/llvm-objcopy")
set(CMAKE_SIZE         "${TRICORE_LLVM_BIN}/llvm-size")
set(CMAKE_AR           "${TRICORE_LLVM_BIN}/llvm-ar")

set(CMAKE_EXECUTABLE_SUFFIX_ASM ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C   ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".elf")

set(TRICORE_CPU_FLAGS_DEFAULT "-mcpu=tc3xx")
set(CMAKE_C_FLAGS_INIT "${TRICORE_CPU_FLAGS_DEFAULT}")
set(CMAKE_ASM_FLAGS_INIT "${TRICORE_CPU_FLAGS_DEFAULT}")
set(CMAKE_CXX_FLAGS_INIT "${TRICORE_CPU_FLAGS_DEFAULT} -fno-exceptions")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${TRICORE_CPU_FLAGS_DEFAULT} -Wl,--cref -Wl,-n")

set(CMAKE_C_FLAGS_DEBUG_INIT "-fomit-frame-pointer -g -O0")
set(CMAKE_ASM_FLAGS_DEBUG_INIT "")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-fomit-frame-pointer -g -O0")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT "")

set(CMAKE_EXPORT_COMPILE_COMMANDS 1)
